# Generated by Django 5.1 on 2024-08-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.TextField(max_length=200, verbose_name='id_producto')),
                ('category', models.TextField(max_length=20, verbose_name='categoria')),
                ('filter_brand', models.TextField(max_length=50, verbose_name='filtro_marca')),
                ('filter_1', models.TextField(max_length=30, verbose_name='filtro_1')),
                ('filter_2', models.TextField(max_length=30, null=True, verbose_name='filtro_2')),
                ('filter_3', models.TextField(max_length=30, null=True, verbose_name='filtro_3')),
                ('filter_4', models.TextField(max_length=90, null=True, verbose_name='filtro_4')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('available', models.BooleanField(default=True, verbose_name='disponible')),
                ('id_catalog', models.TextField(max_length=10, primary_key=True, serialize=False, verbose_name='id_catalogo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='imagen_catalogo')),
                ('description', models.TextField(max_length=255, null=True, verbose_name='descripcion_catalogo')),
                ('retail_price', models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='precio_unidad')),
                ('wholesale_price', models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='precio_mayor')),
                ('lacation_store', models.TextField(max_length=40, null=True, verbose_name='ubicacion_bodega')),
            ],
        ),
    ]
