# Generated by Django 5.1 on 2024-08-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(choices=[('espadin', 'Espadin'), ('control', 'Control'), ('bombillo', 'Bombillo'), ('carcasa', 'Carcasa'), ('mando', 'Mando'), ('sticker', 'Sticker'), ('vacio', 'Vacio'), ('llave', 'Llave'), ('pila', 'Pila'), ('chip', 'Chip'), ('botoneras', 'Botoneras'), ('logo', 'Logo'), ('goma', 'Goma')], max_length=20, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_brand',
            field=models.TextField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Chino', 'Chino'), ('Citroen', 'Citroen'), ('Cr Chery', 'Cr Chery'), ('Dodge-Jeep', 'Dodge-Jeep'), ('Energizer', 'Energizer'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Foton', 'Foton'), ('GP', 'GP'), ('Handy', 'Handy'), ('Hella', 'Hella'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Hyundai-Kia', 'Hyundai-Kia'), ('Kia', 'Kia'), ('Mazda', 'Mazda'), ('Mercedes', 'Mercedes'), ('Mitsubishi', 'Mitsubishi'), ('Murata', 'Murata'), ('Nissan', 'Nissan'), ('Onix', 'Onix'), ('Opel', 'Opel'), ('Originales', 'Originales'), ('Peugeot', 'Peugeot'), ('Q&Q', 'Q&Q'), ('Renault', 'Renault'), ('Sang Yong', 'Sang Yong'), ('Seat', 'Seat'), ('Skoda', 'Skoda'), ('Ssuo', 'Ssuo'), ('Suzuki', 'Suzuki'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Xhorse', 'Xhorse'), ('Yamaha', 'Yamaha'), ('Landrober', 'Landrober'), ('Keydiy-Peugeot', 'Keydiy-Peugeot'), ('Keydiy-Ford', 'Keydiy-Ford'), ('Keydiy', 'Keydiy'), ('Face to Face', 'Face to Face'), ('Keydiy-BMW', 'Keydiy-BMW')], max_length=50, verbose_name='filtro_marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=200, verbose_name='name'),
        ),
    ]
